In [1]:
# fig, ax = plt.subplots(figsize=(20,15))
# y_pos = range(len(list(company_sales.keys())))
# performance = company_sales.values()
# ax.barh(y_pos,performance,height=0.9)
# ax.set_yticks(y_pos, labels=list(company_sales.keys()))
# ax.invert_yaxis()  # labels read top-to-bottom
# # ax.set_xlabel("Company Names")
# ax.set_title("company_sales")
# # up above code belongs to bar

# patches = ax.patches

# for i in range(len(patches)):
#     x = patches[i].get_width()
#     y = patches[i].get_y() + patches[i].get_height() / 2
#     ax.annotate(list(company_sales.values())[i],(x,y),ha="left",fontsize=12)
#     ax.tick_params(axis="both",labelsize=15)
# #this code belongs to numbers or annotations
  



In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 


In [3]:
# fig , ax = plt.subplots(figsize=(16,25))
# y_pos = range(len(list(df["store_primary_category"].value_counts().keys())))
# performance = df["store_primary_category"].value_counts().values
# ax.barh(y_pos,performance,height=0.9,color=[i for i in color_coll])
# ax.set_yticks(y_pos,labels=list(df["store_primary_category"].value_counts().keys()))
# ax.invert_yaxis()

# patches = ax.patches
# for i in range(len(patches)):
#     x = patches[i].get_width()
#     y = patches[i].get_y() + patches[i].get_height()/2
#     ax.annotate(performance[i],(x,y),ha = "left",color=color_coll[i])
#     ax.tick_params(axis="both",labelsize=12)

In [2]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                   "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                            pd.NaT]})

df

name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [5]:
df.size

9

In [5]:
df1 = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "age": [20, 30, 35],
                   "born": [1, 1,1],
                   "cat" : [1,1,0]})

df1

name  age  born  cat
0    Alfred   20     1    1
1    Batman   30     1    1
2  Catwoman   35     1    0

# Variance

In [6]:
# finding variance 
# df1.var()['age']
df1["age"].var()

58.333333333333336

In [7]:
df1["cat"].var()

0.33333333333333337

In [8]:
df1["born"].var()

0.0

In [9]:
# df1["name"].var() # having string in a column while calculating variance will give an error

In [10]:
from statistics import variance
variance(df1["age"])

58.333333333333336

In [11]:
variance(df1["born"])

0

In [12]:
variance(df1["cat"])

0.3333333333333333

In [13]:
# df.dropna(subset=["born"],inplace=True)
# df

In [14]:
for i in df.toy:
    print(i)
    print(type(i))

nan
<class 'float'>
Batmobile
<class 'str'>
Bullwhip
<class 'str'>


In [15]:
df.loc[~df['name'].isna()]

name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

*Iterating through a column and avoiding Nan Values*

In [16]:
for i in range(len(df["toy"])):
    if df['toy'][i] == df['toy'][i]:
        print(df["toy"][i])

Batmobile
Bullwhip


# Sorting Dictionary

In [17]:
footballers_goals = {'Eusebio': 120, 'Cruyff': 104, 'Pele': 150, 'Ronaldo': 132, 'Messi': 125}

sorted_footballers_by_goals = sorted(footballers_goals.items(), key=lambda x:x[1])
print(sorted_footballers_by_goals)

# [('Cruyff', 104), ('Eusebio', 120), ('Messi', 125), ('Ronaldo', 132), ('Pele', 150)]

[('Cruyff', 104), ('Eusebio', 120), ('Messi', 125), ('Ronaldo', 132), ('Pele', 150)]


In [18]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
lb.fit_transform(df["name"])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [19]:
! pip install category_encoders 
import category_encoders

In [20]:
from category_encoders import BinaryEncoder
bi = BinaryEncoder()
bi.fit_transform(df["name"])

name_0  name_1
0       0       1
1       1       0
2       1       1

In [21]:
#Import the libraries
import category_encoders as ce
import pandas as pd

#Create the dataframe
data=pd.DataFrame({'City':['Delhi','Mumbai','Hyderabad','Chennai','Bangalore','Delhi','Hyderabad','Mumbai','Agra']})

#Create an object for Base N Encoding
encoder= ce.BaseNEncoder(cols=['City'],return_df=True,base=4)

#Original Data
data

City
0      Delhi
1     Mumbai
2  Hyderabad
3    Chennai
4  Bangalore
5      Delhi
6  Hyderabad
7     Mumbai
8       Agra

In [22]:
#Fit and Transform Data
data_encoded=encoder.fit_transform(data)
data_encoded

City_0  City_1
0       0       1
1       0       2
2       0       3
3       1       0
4       1       1
5       0       1
6       0       3
7       0       2
8       1       2

In [23]:
df.select_dtypes(["object"]).nunique()

name    3
toy     2
dtype: int64

In [24]:
df.dtypes

name            object
toy             object
born    datetime64[ns]
dtype: object

In [25]:
df

name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [26]:
l = [1,2,4,5,6]
sum(l)

18

# Target Encoding 

In [28]:
#import the libraries
import pandas as pd
import category_encoders as ce

#Create the Dataframe
data=pd.DataFrame({'class':['A','B','C','B','C','A','A','A'],'Marks':[50,30,70,80,45,97,80,68]})

#Create target encoding object
encoder=ce.TargetEncoder(cols='class') 

#Original Data
data

class  Marks
0     A     50
1     B     30
2     C     70
3     B     80
4     C     45
5     A     97
6     A     80
7     A     68

In [29]:
from sklearn.model_selection import train_test_split
X = data.drop("Marks",axis=1)
y = data["Marks"]
X_train,X_test,y_train,y_yest = train_test_split(X,y,test_size=0.2,random_state=0)

In [30]:
#Fit and Transform Train Data
encoder.fit_transform(X_train,y_train)

class
1  60.720993
7  63.211319
3  60.720993
0  63.211319
5  63.211319
4  59.498192

In [31]:
X_train

class
1     B
7     A
3     B
0     A
5     A
4     C

In [32]:
X_test

class
6     A
2     C

In [ ]:
encoder.transform(X_test)
""">>> # A high `smooth` parameter puts more weight on global mean on the categorical
>>> # encoding

>>> # On the other hand, a low `smooth` parameter puts more weight on target
>>> # conditioned on the value of the categorical:"""

# Target Encoding 2 

In [33]:
#Create the Dataframe
data22=pd.DataFrame({'class':['A','B','C','B','B','A','A','A'],
                     'Marks':[50,30,70,80,45,97,80,68]})

data22


class  Marks
0     A     50
1     B     30
2     C     70
3     B     80
4     B     45
5     A     97
6     A     80
7     A     68

In [34]:
from sklearn.model_selection import train_test_split
X = data22.drop("Marks",axis=1)
y = data22["Marks"]
X_train,X_test,y_train,y_yest = train_test_split(X,y,test_size=0.2)

In [ ]:
X_test

class
4     B
7     A

In [35]:
X_train

class
5     A
1     B
2     C
3     B
0     A
4     B

In [36]:
from sklearn.preprocessing import TargetEncoder
te1 = TargetEncoder(target_type="continuous")
te1.fit_transform(X_train,y_train)

array([[50.        ],
       [64.23283113],
       [51.25      ],
       [38.54154669],
       [97.        ],
       [58.79167931]])

In [37]:
from sklearn.preprocessing import TargetEncoder
te2 = TargetEncoder(target_type="continuous",cv=5,smooth="auto",random_state=0)
te2.fit_transform(X_train,y_train)

array([[50.        ],
       [64.23283113],
       [64.25      ],
       [38.54154669],
       [97.        ],
       [57.92962564]])

In [38]:
from sklearn.preprocessing import TargetEncoder
te3 = TargetEncoder(target_type="continuous",cv=5,smooth=5000,random_state=0)
te3.fit_transform(X_train,y_train)

array([[54.9990002 ],
       [68.39764094],
       [64.25      ],
       [58.39164334],
       [64.4065187 ],
       [64.24630148]])

In [39]:
te3.transform(X_test)

array([[62.00459816],
       [62.00459816]])

# Target Encoding Classification

In [40]:
#Create the Dataframe
data222=pd.DataFrame({'class':['A','B','C','B','B','A','A','A'],
                     'Marks':[1,0,0,0,1,1,1,0]})

data222

class  Marks
0     A      1
1     B      0
2     C      0
3     B      0
4     B      1
5     A      1
6     A      1
7     A      0

In [41]:
from sklearn.model_selection import train_test_split
X = data222.drop("Marks",axis=1)
y = data222["Marks"]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [42]:
X_train

class
4     B
0     A
5     A
3     B
2     C
1     B

In [ ]:
X_test

class
4     B
7     A

In [46]:
from sklearn.preprocessing import TargetEncoder
tt2 = TargetEncoder(cv=2,target_type="binary",smooth=2)
tt2.fit_transform(X_train,y_train)

array([[0.22222222],
       [0.55555556],
       [0.77777778],
       [0.22222222],
       [0.66666667],
       [0.58333333]])

In [44]:
tt2.transform(X_test)

array([[0.75],
       [0.75]])

In [ ]:
# class KFoldTargetEncoderTrain(base.BaseEstimator, base.TransformerMixin):

# def __init__(self, colnames,targetName,n_fold=5,verbosity=True,discardOriginal_col=False):

#     self.colnames = colnames
#     self.targetName = targetName
#     self.n_fold = n_fold
#     self.verbosity = verbosity
#     self.discardOriginal_col = discardOriginal_col

# def fit(self, X, y=None):
#     return self


# def transform(self,X):

#     assert(type(self.targetName) == str)
#     assert(type(self.colnames) == str)
#     assert(self.colnames in X.columns)
#     assert(self.targetName in X.columns)

#     mean_of_target = X[self.targetName].mean()
#     kf = KFold(n_splits = self.n_fold, shuffle = False, random_state=2019)

#     col_mean_name = self.colnames + '_' + 'Kfold_Target_Enc'
#     X[col_mean_name] = np.nan

#     for tr_ind, val_ind in kf.split(X):
#         X_tr, X_val = X.iloc[tr_ind], X.iloc[val_ind]
#         X.loc[X.index[val_ind], col_mean_name] = X_val[self.colnames].map(X_tr.groupby(self.colnames)[self.targetName].mean())

#     X[col_mean_name].fillna(mean_of_target, inplace = True)

#     if self.verbosity:

#         encoded_feature = X[col_mean_name].values
#         print('Correlation between the new feature, {} and, {} is {}.'.format(col_mean_name,
#                                                                                   self.targetName,
#                                                                                   np.corrcoef(X[self.targetName].values, encoded_feature)[0][1]))
#     if self.discardOriginal_col:
#         X = X.drop(self.targetName, axis=1)
        

#     return X

# targetc_chid = KFoldTargetEncoderTrain('chid','target',n_fold=5)
# train_df = targetc_chid.fit_transform(train_df)

# for test data 

In [ ]:
# class KFoldTargetEncoderTest(base.BaseEstimator, base.TransformerMixin):
    
#     def __init__(self,train,colNames,encodedName):
        
#         self.train = train
#         self.colNames = colNames
#         self.encodedName = encodedName
        
#     def fit(self, X, y=None):
#         return self
#     def transform(self,X):
#         mean =  self.train[[self.colNames,
#                 self.encodedName]].groupby(
#                                 self.colNames).mean().reset_index() 

#         dd = {}
#         for row in tqdm(mean.itertuples(index=False)):
#             dd[row[0]] = row[1]
#         X[self.encodedName] = X[self.colNames]
#         X[self.encodedName] = X[self.encodedName].map(dd.get)
#         return X
    
# test_targetc_chid = KFoldTargetEncoderTest(train_df,'chid','chid_Kfold_Target_Enc')
# valid_df = test_targetc_chid.fit_transform(valid_df)